package App;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

public class BaseDatosMedicamentos extends javax.swing.JFrame {

    public BaseDatosMedicamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        JscrollTablaBase = new javax.swing.JScrollPane();
        JTableBaseDatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        JbuttonEliminar = new javax.swing.JButton();
        JbuttonEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JlabelID = new javax.swing.JLabel();
        txtFieldCategoriaForm = new javax.swing.JTextField();
        txtFielNombreForm = new javax.swing.JTextField();
        JFilterCategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("BASE DATOS MEDICAMENTOS ");

        JTableBaseDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableBaseDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableBaseDatosMouseClicked(evt);
            }
        });
        JscrollTablaBase.setViewportView(JTableBaseDatos);
        if (JTableBaseDatos.getColumnModel().getColumnCount() > 0) {
            JTableBaseDatos.getColumnModel().getColumn(0).setMinWidth(50);
            JTableBaseDatos.getColumnModel().getColumn(0).setPreferredWidth(100);
            JTableBaseDatos.getColumnModel().getColumn(0).setMaxWidth(100);
            JTableBaseDatos.getColumnModel().getColumn(2).setMinWidth(150);
            JTableBaseDatos.getColumnModel().getColumn(2).setPreferredWidth(300);
            JTableBaseDatos.getColumnModel().getColumn(2).setMaxWidth(300);
        }
        //style table
        JTableBaseDatos.getTableHeader().setFont(new java.awt.Font("Arial Black", 1, 14));
        JTableBaseDatos.getTableHeader().setForeground(new java.awt.Color(0, 153, 153));
        JTableBaseDatos.getTableHeader().setOpaque(false);
        JTableBaseDatos.getTableHeader().setBackground(new java.awt.Color(255, 255, 255));
        JTableBaseDatos.getTableHeader().setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        JTableBaseDatos.setRowHeight(25);

        JTableBaseDatos.setFont(new java.awt.Font("Arial", 0, 14));
        JTableBaseDatos.setForeground(new java.awt.Color(51, 51, 51));
        JTableBaseDatos.setSelectionBackground(new java.awt.Color(0, 153, 153));
        JTableBaseDatos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        JTableBaseDatos.setGridColor(new java.awt.Color(0, 153, 153));
        JTableBaseDatos.setShowVerticalLines(false);
        JTableBaseDatos.setShowHorizontalLines(false);
        JTableBaseDatos.setShowGrid(true);

        //center header table
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        JTableBaseDatos.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        JTableBaseDatos.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        JTableBaseDatos.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );

        //center table data

        DefaultTableCellRenderer leftRenderer = new DefaultTableCellRenderer();
        leftRenderer.setHorizontalAlignment( JLabel.LEFT );
        JTableBaseDatos.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        JTableBaseDatos.getColumnModel().getColumn(1).setCellRenderer( leftRenderer );
        JTableBaseDatos.getColumnModel().getColumn(2).setCellRenderer( leftRenderer );

        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        JbuttonEliminar.setBackground(new java.awt.Color(255, 102, 102));
        JbuttonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        JbuttonEliminar.setText("Eliminar");
        JbuttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonEliminarActionPerformed(evt);
            }
        });

        JbuttonEditar.setBackground(new java.awt.Color(51, 51, 255));
        JbuttonEditar.setForeground(new java.awt.Color(255, 255, 255));
        JbuttonEditar.setText("Editar");
        JbuttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonEditarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Categoria");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Id");

        JlabelID.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlabelID.setForeground(new java.awt.Color(51, 51, 51));

        txtFieldCategoriaForm.setBackground(new java.awt.Color(0, 153, 153));
        txtFieldCategoriaForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFieldCategoriaForm.setForeground(new java.awt.Color(255, 255, 255));

        txtFielNombreForm.setBackground(new java.awt.Color(0, 153, 153));
        txtFielNombreForm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtFielNombreForm.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JlabelID)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 451, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(304, 304, 304))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JbuttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFielNombreForm, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFieldCategoriaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(JbuttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(288, 288, 288))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JlabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFielNombreForm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldCategoriaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbuttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbuttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        JFilterCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JFilterCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas" }));
        JFilterCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                JFilterCategoryItemStateChanged(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Filtrar por categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JFilterCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGap(298, 298, 298))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(JscrollTablaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)))
                .addComponent(JFilterCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(JscrollTablaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTableBaseDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableBaseDatosMouseClicked
        // TODO add your handling code here:
        int fila = JTableBaseDatos.rowAtPoint(evt.getPoint());

        if (fila > -1) {
            JlabelID.setText(JTableBaseDatos.getValueAt(fila, 0).toString());
            txtFielNombreForm.setText(JTableBaseDatos.getValueAt(fila, 1).toString());
            String categoria = JTableBaseDatos.getValueAt(fila, 2).toString();

            txtFieldCategoriaForm.setText(categoria);
        }

    }//GEN-LAST:event_JTableBaseDatosMouseClicked

    private void JbuttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonEditarActionPerformed
        // TODO add your handling code here:
        if (txtFielNombreForm == null || txtFielNombreForm.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un nombre");
        } else {
            String categoria = "";
            categoria = txtFieldCategoriaForm.getText();
            int id = Integer.parseInt(JlabelID.getText());
            String nombre = txtFielNombreForm.getText();
            String sql = "UPDATE medicamentos SET nombre = '" + nombre + "', categoria = '" + categoria + "' WHERE id = " + id;
            try {
                Connection con = conexion.getConexion();
                PreparedStatement ps = con.prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Medicamento actualizado");
                limpiar();
                mostrarDatos();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_JbuttonEditarActionPerformed

    private void JbuttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonEliminarActionPerformed
        // TODO add your handling code here:
        int fila = JTableBaseDatos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        } else {
            int id = Integer.parseInt(JlabelID.getText());
            String sql = "DELETE FROM medicamentos WHERE id = " + id;
            try {
                Connection con = conexion.getConexion();
                PreparedStatement ps = con.prepareStatement(sql);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Medicamento eliminado");
                limpiar();
                mostrarDatos();
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }


    }//GEN-LAST:event_JbuttonEliminarActionPerformed

    private void JFilterCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_JFilterCategoryItemStateChanged
        // TODO add your handling code here:
        String categoria = JFilterCategory.getSelectedItem().toString();
        if (categoria.equals("Todas")) {
            mostrarDatos();
            
        } else {
            String sql = "SELECT * FROM medicamentos WHERE categoria = '" + categoria + "'";
            DefaultTableModel modelo = (DefaultTableModel) JTableBaseDatos.getModel();
            //limpiar tabla
            modelo.setRowCount(0);
            //obtener datos de la base de datos
            try {
                Connection con = conexion.getConexion();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    Object[] fila = new Object[3];
                    fila[0] = rs.getInt("id");
                    fila[1] = rs.getString("nombre");
                    fila[2] = rs.getString("categoria");
                    modelo.addRow(fila);
                }
                con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_JFilterCategoryItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaseDatosMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaseDatosMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaseDatosMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaseDatosMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaseDatosMedicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> JFilterCategory;
    public javax.swing.JTable JTableBaseDatos;
    private javax.swing.JButton JbuttonEditar;
    private javax.swing.JButton JbuttonEliminar;
    private javax.swing.JLabel JlabelID;
    public javax.swing.JScrollPane JscrollTablaBase;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtFielNombreForm;
    private javax.swing.JTextField txtFieldCategoriaForm;
    // End of variables declaration//GEN-END:variables

    private void limpiar() {
        JlabelID.setText("");
        txtFielNombreForm.setText("");
        
    }

    private void mostrarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) JTableBaseDatos.getModel();
        //limpiar tabla
        modelo.setRowCount(0);
        //obtener datos de la base de datos
        try {
            Connection con = conexion.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM medicamentos");
            while (rs.next()) {
                Object[] fila = new Object[3];
                fila[0] = rs.getInt("id");
                fila[1] = rs.getString("nombre");
                fila[2] = rs.getString("categoria");
                modelo.addRow(fila);
            }

            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void cargarCategorias() {
        //si combo solo tiene Todas, agregar categorias
        try {
            Connection con = conexion.getConexion();
            Statement st = con.createStatement();
            if (JFilterCategory.getItemCount() == 1) {
                //obtener categorias de la base de datos
                ResultSet rs2 = st.executeQuery("SELECT DISTINCT categoria FROM medicamentos");
                while (rs2.next()) {
                    JFilterCategory.addItem(rs2.getString("categoria"));
                }
            } else if (JFilterCategory.getItemCount() > 1) {
                //si hay mas de una categoria, limpiar combo
                JFilterCategory.removeAllItems();
                JFilterCategory.addItem("Todas");
                //obtener categorias de la base de datos
                ResultSet rs2 = st.executeQuery("SELECT DISTINCT categoria FROM medicamentos");
                while (rs2.next()) {
                    JFilterCategory.addItem(rs2.getString("categoria"));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
}
